### ISSUE TITLE
SIMDPirates is deprecated

### ISSUE THREAD

**Issue by chriselrod** [tknopp/RegularizedLeastSquares.jl#19]
I can help with the transition to VectorizationBase.jl (which you already depend on) this weekend.
https://github.com/chriselrod/SIMDPirates.jl/issues/15

Is this file the only place it is being used?
https://github.com/tknopp/RegularizedLeastSquares.jl/blob/271ae115dea8c351f71c6f3abaeb78aeee182b1a/src/Kaczmarz.jl#L279
If so, it should only take a few minutes. Is it covered in the tests?

**Comment by tknopp** [comment]
Thanks Chris! I ping @hofmannmartin who has written that code. As far as I can see it is the only case where we use SIMDPirates. I had a look ad codecov but was not able to determine if we test this code path.

**Comment by hofmannmartin** [comment]
It is only one code block which needs to be updated. It starts at 

https://github.com/tknopp/RegularizedLeastSquares.jl/blob/5b84f349503614546f0a5d4e8edf15e25455ae2b/src/Kaczmarz.jl#L259

and is tested in 

https://github.com/tknopp/RegularizedLeastSquares.jl/blob/188d5243572701d1ff601198f471656948db472d/test/Kaczmarz.jl#L1

However, the code was written 10 month ago and uses quite old versions of `SIMDPirates` and `VectorizationBase` (0.6.8 and 0.7.1). I also make quite extensive use of explicit SIMD operations, inspired by your [julia discourse comments](https://discourse.julialang.org/t/why-mul-is-so-fast/31436/6). Does this complicate things @chriselrod?
