### ISSUE TITLE
Lazy transpose now in LInearAlgebra

### ISSUE THREAD

**Issue by hofmannmartin** [tknopp/RegularizedLeastSquares.jl#3]
lazy transpose is now standard in `LinearAlgebra`, where `adjoint` and `transpose` are defined. Would improve our code if we would use the stuff from `LinearAlgebra`.

**Comment by tknopp** [comment]
yes, that needs refactoring.

**Comment by tknopp** [comment]
I have switch to the lazy transposed type from LinearAlgebra. We basically shipped the same version in the julia 0.6 days, so the switch was simple. Its changed in MPIReco accordingly.
