### ISSUE TITLE
Type Stability of Identity Operator

### ISSUE THREAD

**Issue by alexjaffray** [tknopp/RegularizedLeastSquares.jl#35]
I have been debugging the CGNR code in MRIReco.jl to make sure that arbitrary type (i.e 32-bit) reconstructions work as expected, and have come across a bug in both SparsityOperators and RegularizedLeastSquares.jl. It seems as though a weighting operator created using LinearAlgebra.I always has a 64-bit type.  When doing composite operations, for example doing 32-bit SENSE and Off-resonance reconstruction using CGNR as the solver, this results in an error, as the composite operation is composed of both 32 and 64 bit operators.

One can reproduce the error with the following code: 

  ```
using MRIReco

numCoils = 32
N = 64
T = ComplexF32
  ISim = T.(shepp_logan(N))
  ISim = circularShutterFreq!(ISim,1)

  coilsens = T.(birdcageSensitivity(N, numCoils, 1.5))
  cmap = T.(1im*quadraticFieldmap(N,N,125*2pi))

  # simulation parameters
  params = Dict{Symbol, Any}()
  params[:simulation] = "fast"
  params[:trajName] = "Spiral"
  params[:numProfiles] = 1
  params[:numSamplingPerProfile] = div(N*N,2)
  params[:windings] = div(N,4)
  params[:AQ] = 3.0e-2
  params[:senseMaps] = coilsens
  params[:correctionMap] = cmap[:,:,1]

  # do simulation
  acqData = simulation(ISim, params)

  # reco parameters
  params = Dict{Symbol, Any}()
  params[:reco] = "multiCoil" #"standard"
  params[:reconSize] = (N,N)
  params[:regularization] = "L2"
  params[:iterations] = 20
  params[:solver] = "cgnr"
  params[:solverInfo] = SolverInfo(T)
  params[:senseMaps] = coilsens
  params[:correctionMap] = cmap[:,:,1]

  Ireco = reconstruction(acqData, params)
```

I suggest switching to LinearOperators.opEye() as an alternative to LinearAlgebra.I, since it is natively type-stable when applied to any vector (i.e it preserves the type of the vector and acts as an operator of the same type at run-time). This gets rid of the error for me, but I don't know if it has repercussions down the line in other packages. Let me know if you want me to make a PR with my changes, I have a fork of both repos.

**Comment by tknopp** [comment]
https://github.com/tknopp/RegularizedLeastSquares.jl/commit/8c0956a92ed0a32fba0c68953e031aafa5940d96

**Comment by tknopp** [comment]
This seems to be fixed. Please reopen, if there are still issues.

**Comment by alexjaffray** [comment]
Thanks! I did indeed mean the second case above.
