### ISSUE TITLE
Rename package to `RegularizedLeastSquares.jl`

### ISSUE THREAD

**Issue by hofmannmartin** [tknopp/RegularizedLeastSquares.jl#4]
What we do is in principle least squares with regularization. I therefore propose to rename our package.

This would also quite well fit together with the package `LinearLeastSquares`, which does least squares with linear constraints(https://github.com/davidlizeng/LinearLeastSquares.jl).

There is also a package for the fitting of non linear models `LsqFit`, which is in `JuliaNLSolvers`. However, since we have restricted ourselves to linear problems, the relation is more lose.

What do you think @migrosser @tknopp

**Comment by migrosser** [comment]
I agree. This definitely captures what we are doing quite well.

**Comment by tknopp** [comment]
done. I fear that this will break code everywhere...

**Comment by tknopp** [comment]
docs are not deployed currently, see https://travis-ci.org/tknopp/RegularizedLeastSquares.jl/jobs/447358799
