### ISSUE TITLE
Use the iterator interface for iterative solvers

### ISSUE THREAD

**Issue by hofmannmartin** [tknopp/RegularizedLeastSquares.jl#5]
While searching for some more inspiration for our package, I stumbled across the package `IterativeSolver`. They use the iterator interface for their solvers and I quite like that (see e.g. https://github.com/JuliaMath/IterativeSolvers.jl/blob/master/src/cg.jl).

**Comment by tknopp** [comment]
Its nice because its the iterator interface but actually I don't see a pressing advantage. At least how it is currently used in IterativeSolvers.jl. The most pressing issue of this package is more the surface syntax.

**Comment by tknopp** [comment]
This was actually implemented by @migrosser once upon a time.
